sudo: false
cache:
  directories:
    - "$HOME/.m2"
language: java
script:
  - mvn -B -T2 -fae -Djava.awt.headless=true -Dall clean install
notifications:
  email: false
  on_failure: never
env: GDAL_LIBRARY_NAME=disabled_see_geot-4733
os:
  - linux
  - osx
matrix:
#  allow_failures:
#    - os: osx
  include:
  # additional builds on linux w/ openjdk7 and oraclejdk8
    - os: linux
      jdk: openjdk7
    - os: linux
      jdk: oraclejdk8
before_install:
   # JAVA_HOME is not available on OSX, set it to allow Maven run
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
